### ISSUE TITLE
Add get-ssh-cmd action

### ISSUE THREAD

**Issue by jneo8** [canonical/charm-cloudsupport#6]
Create an action to get ssh cmd to connect to instances.

This should support both ovs and ovn

------------------------------------
Imported from Launchpad using lp2gh.

 * date created: 2022-03-31T13:55:09Z
 * owner: [peppepetra](https://launchpad.net/~peppepetra)
 * assignee: [None](https://launchpad.net/~None)
 
 
 * the launchpad [url](https://bugs.launchpad.net/bugs/1967298)

**Comment by Pjack** [comment]
https://code.launchpad.net/~peppepetra/charm-cloudsupport/+git/charm-cloudsupport/+merge/417817
